package com.example.presenter.theme

import androidx.compose.ui.graphics.Color

val dark_primary = Color(0xFF393D65)
val dark_onPrimary = Color(0xFFFFFFFF)
val dark_primaryContainer = Color(0xFFEBEBEB)
val dark_onPrimaryContainer = Color(0xFF002336)
val dark_secondary = Color(0xFF393D65)
val dark_onSecondary = Color(0xFFFFFFFF)
val dark_secondaryContainer = Color(0xFFE5F1EF)
val dark_onSecondaryContainer = Color(0xFF001F27)
val dark_tertiary = Color(0xFF393D65)
val dark_onTertiary = Color(0xFFFFFFFF)
val dark_tertiaryContainer = Color(0xFFFFDADD)
val dark_onTertiaryContainer = Color(0xFF40000D)
val dark_error = Color(0xFFDD453C)
val dark_errorContainer = Color(0xFFF9DEDC)
val dark_onError = Color(0xFFFFFFFF)
val dark_onErrorContainer = Color(0xFF410E0B)
val dark_background = Color(0xFF171717)
val dark_onBackground = Color(0xFFFFFFFF)
val dark_surface = Color(0xFF262626)
val dark_onSurface = Color(0xFFBDBDBD)
val dark_surfaceVariant = Color(0xFF2E2E2E)
val dark_onSurfaceVariant = Color(0xFFBDBDBD)
val dark_outline = Color(0xFF9B9B9B)
val dark_outlineVariant = Color(0xFF272727)
val dark_inverseOnSurface = Color(0xFFEFF1F1)
val dark_inverseSurface = Color(0xFF2D3132)
val dark_inversePrimary = Color(0xFF41B4D2)